#!/bin/bash
# Pyramid OpenShift post-deploy pre-start configuration

APP=pyramidapp

if [[ -e $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/bin/activate_virtenv ]]; then
    # Python 2.7 (and 3.3?)
    source $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/bin/activate_virtenv
else
    # Python 2.6
    source $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/virtenv/bin/activate
fi

# Have apache serve up all of our static resources
echo "Symlinking static resources from $APP/public"
ln -s $OPENSHIFT_REPO_DIR/wsgi/$APP/$APP/static/* $OPENSHIFT_REPO_DIR/wsgi/static/

cd $OPENSHIFT_REPO_DIR/wsgi/$APP

# We're not doing 'install' to save space.
python setup.py develop
