#!/bin/bash
# Pyramid OpenShift post-deploy pre-start configuration

APP=pyramidapp

if [[ -e $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/bin/activate_virtenv ]]; then
    # Python 2.7 (and 3.3?)
    source $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/bin/activate_virtenv
else
    # Python 2.6
    source $OPENSHIFT_PRIMARY_CARTRIDGE_DIR/virtenv/bin/activate
fi

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
    echo 1>&2
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    echo 1>&2
    exit 5
fi

cd $OPENSHIFT_REPO_DIR/wsgi/$APP

# Initialize our database
if [ ! -e $OPENSHIFT_DATA_DIR/DB_INITIALIZED ]; then
    echo "Initializing database"
    paster setup-app production.ini
    touch $OPENSHIFT_DATA_DIR/DB_INITIALIZED
fi

# Run the test suite automatically
# At the moment failure does not prevent the code from getting deployed
echo "Running the test suite"
unset OPENSHIFT_APP_NAME
python setup.py test
