#!/usr/bin/python
import os, sys

here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(here, 'pyramidapp'))
config = os.path.join(here, 'pyramidapp', 'production.ini')

virtenv = os.path.join(os.environ['OPENSHIFT_PRIMARY_CARTRIDGE_DIR'], 'virtenv')
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

import logging.config
logging.config.fileConfig(config)

from pyramid.paster import get_app
application = get_app(config, 'main', options={
    #'db_uri': '{OPENSHIFT_MYSQL_DB_URL}{OPENSHIFT_APP_NAME}'.format(**os.environ),
    'data_dir': '{OPENSHIFT_DATA_DIR}'.format(**os.environ),
})

if __name__  == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    httpd.handle_request()
 
